language: java
env:
  global:
    - CI_NAME=travis-ci
    - TESTFAIRY_UPLOAD_VERSION='1.0.0'
    - secure: a3Vq3i0ClDu6jg/TAVquAAHnx86eXEKRoyE8A2sUfwIfhUHfAe/uXQvoyl7a7ojDV/SqPMjcnP6lJ5h6n0+JOuAXDgcH8WlY4a7976yhTxdQyf1ULbIkbtLJ6qdedlTbBpdyqvntMhrZ3XskEasHRJYJ8V9r7Y/2rqXmttibP9t+qOwZJ8t2X/cv2uHxLK3RURDPHJMYorQUNBK8IY9SQRPAvTTv9ex2/o7ecszDmO08BE4zBnE7aDVie7+nT8/aRs2hmloPljnad9kR9OI1F222+FzBuWXhftFvRWUKhAf5QXcWcWcQCyWP+iAFQK0GzKPhRRklPuisBjO23V2xw+209VfqBwFp8fEf6AyDi5Y9MGt2/d7+d9fqR73z/8lZoewGcCdCorPk1m/R0FCtoh7I64FPreGQNLolHJMdta1msW8ddf09R/TxJPY7XUdr2cIEPKKxaWvFhcpAleEMAmttpwTaSWb2WGqCwMghgyJDglPG19S7Lf1E50rU3j6oyKX4+OtOWUZv9y1or3VQlFfDQdeTbahqUu9NfI3b3fp2mdtOrQMVadvRvpJJs6pmC4OrmmB/J3zvPuJvRzFFy0hkpV56dxjNNOktR2UKGQin9DX8+MataRGBTZRJHWfdpT2NCVv5BULKSHCN+Sf5F/nKGCriNoZoW7bDWabX8mI=
script:
- ./gradlew jar cobertura coveralls
before_deploy:
- sed -i'' "s/public static final String VERSION = .*/public static final String VERSION = \"${TRAVIS_TAG}\";/g" ./src/main/java/com/testfairy/uploader/cli/Config.java
- ./gradlew jar
- zip -j9 testfairy-uploader-${TRAVIS_TAG}.zip "build/libs/testfairy-uploader.jar" "testfairy-uploader" "testfairy-uploader.bat"
deploy:
  provider: releases
  api_key:
    secure: HDG4U7mi6i1WLu/IDd7PwWtWxh5snRnm5PyoN8K8i1omzWciaDrIHblvOETmbXCq60hWYJQzeF6ow7ck0tj3ASflI0S0KDGB7lEuAOPChBs7X8lD3NMdPHF3qXrTDIbQp00yOgGzcUeLy7it1QcY2iiSvKQ0rPhbkXqX5CqChTYcadWXSO0F4BEIMPG95neIHdqmIXE9r2SQ50EvO9Eyqc4sGfjJBq+w/Hr1x+ucQTanP8krf0Zjtmn90fHK7UXt5qxcSdRJ5azwp7SPcf2IxWvJB7L48C1ktQcjt9uWMZ3hJjuqNcU1LhG71GtTy7YAreMM1U16pG4T5b3xJ16k43UoPJQJYwGqPDHeaNtAap77pWkFj2/t9pd/aaVu69YkoExc2L0Srhobk0s3yQAxUEJa4xwYqZPFaXsS6pIV3769/i+Gfjec2VA8QGEWZ5lcoZPO5l1iDEtOvTvsYGoF8AsqCWs0DbKrYv824rfR2mfOgt/xpt+1bY+GvI0whuCY9TSyUWZSa+cwHHh53bmSOKBAMa0T1cPdu9vdO1oAN+7RnbaixZFa1Ro3mKUX9LyVAZJEa9YoaFbjuabBknPCvHn+WHBGB/H+w/KZ6emCfjbknyO4wSruf/tsN3ZNA5ZcDa0RrghWQux5rEQ4XlpuG6Hv4PtMSwuiyQKy9tIv32A=
  file: testfairy-uploader-${TRAVIS_TAG}.zip
  on:
    repo: testfairy/testfairy-uploader-cli
    tags: true
    branch: master
