language: java
env:
  global:
    - CI_NAME=travis-ci
    - TESTFAIRY_UPLOAD_VERSION='1.0.0'
    - secure: a3Vq3i0ClDu6jg/TAVquAAHnx86eXEKRoyE8A2sUfwIfhUHfAe/uXQvoyl7a7ojDV/SqPMjcnP6lJ5h6n0+JOuAXDgcH8WlY4a7976yhTxdQyf1ULbIkbtLJ6qdedlTbBpdyqvntMhrZ3XskEasHRJYJ8V9r7Y/2rqXmttibP9t+qOwZJ8t2X/cv2uHxLK3RURDPHJMYorQUNBK8IY9SQRPAvTTv9ex2/o7ecszDmO08BE4zBnE7aDVie7+nT8/aRs2hmloPljnad9kR9OI1F222+FzBuWXhftFvRWUKhAf5QXcWcWcQCyWP+iAFQK0GzKPhRRklPuisBjO23V2xw+209VfqBwFp8fEf6AyDi5Y9MGt2/d7+d9fqR73z/8lZoewGcCdCorPk1m/R0FCtoh7I64FPreGQNLolHJMdta1msW8ddf09R/TxJPY7XUdr2cIEPKKxaWvFhcpAleEMAmttpwTaSWb2WGqCwMghgyJDglPG19S7Lf1E50rU3j6oyKX4+OtOWUZv9y1or3VQlFfDQdeTbahqUu9NfI3b3fp2mdtOrQMVadvRvpJJs6pmC4OrmmB/J3zvPuJvRzFFy0hkpV56dxjNNOktR2UKGQin9DX8+MataRGBTZRJHWfdpT2NCVv5BULKSHCN+Sf5F/nKGCriNoZoW7bDWabX8mI=
script:
- ./gradlew jar cobertura coveralls
before_deploy:
- sed -i'' "s/public static final String VERSION = .*/public static final String VERSION = \"${TRAVIS_TAG}\";/g" ./src/main/java/com/testfairy/uploader/cli/Config.java
- ./gradlew jar
- zip -j9 testfairy-uploader-${TRAVIS_TAG}.zip "build/libs/testfairy-uploader.jar" "testfairy-uploader" "testfairy-uploader.bat"
deploy:
  provider: releases
  api_key:
    secure: is/pHo24rh0LQyV4ctyvDI0kLzGGfT12Yed2SVEYOilcKACtfoBB0Z9+lkHH+p0rUYSStL3GFx7lGNT3vyix3oOtF169kNskQ7ulAS9npdtUc2j82CXJPiACfA5p3UjsTGoYMsNaS8zNj/F6TsXMhlG1sXBYhugcyekRnAtu9kqolk9kjMyMGCn8CXQklsPDWeb8WWgHn3rL4PP90eEZn67nRYDqgfQyp5RX/m42p3p0BVEDDyQpeeQjEMZklF5fLx1HdtQ/FUrVCdu7FycHhIQBKvzJUAppnA841xfuoYHv61D1Bg3hW6+k1fEP1X0JUHD5Ji6k30NVF5ci1pDPYCH++UhCk9tZiRKNRrvvw17tWoQW2IpTcri4N1DFgPpVFqBOA0F40dD39Bu0KmnY63egiZx1LaO6hb4q5OzhMiWORdDxRfUWiO4h4nMwIsDlcRtgB4npIzqhWhbSx0I7jga0opS6EAU/v/henKRQ3Vf3rqg9CkpRYkNovo3jJ7RfV9JLYFRhc0lEzyAJ/34ahmpZbJjezN7SxWGmnc6iHFcTTHwAX9gi1WyWFH1yQKbh2nhAUi1rePjA6siqVc8+5hTw/cGkqQuxj18j0WnAJ1JmY1qxIzf9jZasf5dyun8Zu9rheOd5RdnMu/QqfscQZToEbHxMPQZQJmTx94+TDEU=
  file: testfairy-uploader-${TRAVIS_TAG}.zip
  on:
    repo: testfairy/testfairy-uploader-cli
    tags: true
    branch: master
